services:
  leviathan:
    container_name: leviathan
    #image: your-builded_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8397:7000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
