name: Build & Push Docker Image

on:
  # Si attiva ogni volta che fai il push sul branch main
  push:
    branches: [ "main" ]
  # Permette l'avvio manuale dal pannello Actions
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      # Configura l'emulatore per compilare per ARM64 (necessario per Oracle Cloud)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configura il sistema di build avanzato di Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login al GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compila e Carica l'immagine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Compila per PC e per Oracle ARM64
          platforms: linux/amd64,linux/arm64
          # Usa il nome corretto della repo e i tag corretti
          tags: |
            ghcr.io/${{ github.repository }}:main
            ghcr.io/${{ github.repository }}:latest
