name: Build & Push Docker Image

on:
  # Permette l'avvio manuale dal pannello Actions
  workflow_dispatch:
  
  # Si attiva automaticamente al termine del sync


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Esegue se avviato manualmente OPPURE se il sync è riuscito
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Scarica il codice
        uses: actions/checkout@v4

      # Configura l'emulatore per compilare per ARM64 (necessario per Oracle Cloud)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configura il sistema di build avanzato di Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login al GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compila e Carica l'immagine
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Crea l'immagine sia per PC (amd64) che per Oracle/Raspberry (arm64)
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/alessiocav2004-byte/icvfork:latest
